# coding: utf-8

"""
    Visier Profile Management APIs

    Visier APIs for managing the profiles assigned to users

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from visier_profile_management_python_sdk import schemas  # noqa: F401


class LocalTenantProfileAssignmentResponseDTO(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            errors = schemas.BoolSchema
            
            
            class badUserIds(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['UserIdErrorDTO']:
                        return UserIdErrorDTO
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['UserIdErrorDTO'], typing.List['UserIdErrorDTO']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'badUserIds':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'UserIdErrorDTO':
                    return super().__getitem__(i)
            
            
            class failedAssignments(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['FailedLocalTenantProfileAssignmentDTO']:
                        return FailedLocalTenantProfileAssignmentDTO
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['FailedLocalTenantProfileAssignmentDTO'], typing.List['FailedLocalTenantProfileAssignmentDTO']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'failedAssignments':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'FailedLocalTenantProfileAssignmentDTO':
                    return super().__getitem__(i)
            
            
            class successfulAssignments(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['SuccessfulLocalTenantProfileAssignmentDTO']:
                        return SuccessfulLocalTenantProfileAssignmentDTO
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['SuccessfulLocalTenantProfileAssignmentDTO'], typing.List['SuccessfulLocalTenantProfileAssignmentDTO']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'successfulAssignments':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'SuccessfulLocalTenantProfileAssignmentDTO':
                    return super().__getitem__(i)
            __annotations__ = {
                "errors": errors,
                "badUserIds": badUserIds,
                "failedAssignments": failedAssignments,
                "successfulAssignments": successfulAssignments,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["errors"]) -> MetaOapg.properties.errors: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["badUserIds"]) -> MetaOapg.properties.badUserIds: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["failedAssignments"]) -> MetaOapg.properties.failedAssignments: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["successfulAssignments"]) -> MetaOapg.properties.successfulAssignments: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["errors", "badUserIds", "failedAssignments", "successfulAssignments", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["errors"]) -> typing.Union[MetaOapg.properties.errors, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["badUserIds"]) -> typing.Union[MetaOapg.properties.badUserIds, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["failedAssignments"]) -> typing.Union[MetaOapg.properties.failedAssignments, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["successfulAssignments"]) -> typing.Union[MetaOapg.properties.successfulAssignments, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["errors", "badUserIds", "failedAssignments", "successfulAssignments", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        errors: typing.Union[MetaOapg.properties.errors, bool, schemas.Unset] = schemas.unset,
        badUserIds: typing.Union[MetaOapg.properties.badUserIds, list, tuple, schemas.Unset] = schemas.unset,
        failedAssignments: typing.Union[MetaOapg.properties.failedAssignments, list, tuple, schemas.Unset] = schemas.unset,
        successfulAssignments: typing.Union[MetaOapg.properties.successfulAssignments, list, tuple, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'LocalTenantProfileAssignmentResponseDTO':
        return super().__new__(
            cls,
            *args,
            errors=errors,
            badUserIds=badUserIds,
            failedAssignments=failedAssignments,
            successfulAssignments=successfulAssignments,
            _configuration=_configuration,
            **kwargs,
        )

from visier_profile_management_python_sdk.model.failed_local_tenant_profile_assignment_dto import FailedLocalTenantProfileAssignmentDTO
from visier_profile_management_python_sdk.model.successful_local_tenant_profile_assignment_dto import SuccessfulLocalTenantProfileAssignmentDTO
from visier_profile_management_python_sdk.model.user_id_error_dto import UserIdErrorDTO
