# coding: utf-8

"""
    Visier Profile Management APIs

    Visier APIs for managing the profiles assigned to users

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from visier_profile_management_python_sdk import schemas  # noqa: F401


class LocalTenantProfileRevokeRequestDTO(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def targetUserIds() -> typing.Type['LocalTenantProfileRevokeRequestDTOTargetUserIds']:
                return LocalTenantProfileRevokeRequestDTOTargetUserIds
            __annotations__ = {
                "targetUserIds": targetUserIds,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["targetUserIds"]) -> 'LocalTenantProfileRevokeRequestDTOTargetUserIds': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["targetUserIds", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["targetUserIds"]) -> typing.Union['LocalTenantProfileRevokeRequestDTOTargetUserIds', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["targetUserIds", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        targetUserIds: typing.Union['LocalTenantProfileRevokeRequestDTOTargetUserIds', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'LocalTenantProfileRevokeRequestDTO':
        return super().__new__(
            cls,
            *args,
            targetUserIds=targetUserIds,
            _configuration=_configuration,
            **kwargs,
        )

from visier_profile_management_python_sdk.model.local_tenant_profile_revoke_request_dto_target_user_ids import LocalTenantProfileRevokeRequestDTOTargetUserIds
