# coding: utf-8

"""
    Visier Profile Management APIs

    Visier APIs for managing the profiles assigned to users

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

import unittest
from unittest.mock import patch

import urllib3

import visier_profile_management_python_sdk
from visier_profile_management_python_sdk.paths.v1_admin_profiles_profile_id import get
from visier_profile_management_python_sdk import configuration, schemas, api_client

from .. import ApiTestMixin


class TestV1AdminProfilesProfileId(ApiTestMixin, unittest.TestCase):
    """
    V1AdminProfilesProfileId unit test stubs
        Retrieve the details of a profile
    """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    response_status = 200




if __name__ == '__main__':
    unittest.main()
