# coding: utf-8

"""
    Visier Profile Management APIs

    Visier APIs for managing the profiles assigned to users

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from visier_profile_management_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from visier_profile_management_python_sdk.api_response import AsyncGeneratorResponse
from visier_profile_management_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from visier_profile_management_python_sdk import schemas  # noqa: F401

from visier_profile_management_python_sdk.model.status import Status as StatusSchema
from visier_profile_management_python_sdk.model.local_tenant_profile_assignment_request_dto import LocalTenantProfileAssignmentRequestDTO as LocalTenantProfileAssignmentRequestDTOSchema
from visier_profile_management_python_sdk.model.local_tenant_profile_assignment_response_dto import LocalTenantProfileAssignmentResponseDTO as LocalTenantProfileAssignmentResponseDTOSchema
from visier_profile_management_python_sdk.model.local_tenant_profile_assignment_request_dto_target_user_ids import LocalTenantProfileAssignmentRequestDTOTargetUserIds as LocalTenantProfileAssignmentRequestDTOTargetUserIdsSchema

from visier_profile_management_python_sdk.type.local_tenant_profile_assignment_request_dto_target_user_ids import LocalTenantProfileAssignmentRequestDTOTargetUserIds
from visier_profile_management_python_sdk.type.local_tenant_profile_assignment_request_dto import LocalTenantProfileAssignmentRequestDTO
from visier_profile_management_python_sdk.type.local_tenant_profile_assignment_response_dto import LocalTenantProfileAssignmentResponseDTO
from visier_profile_management_python_sdk.type.status import Status

from ...api_client import Dictionary
from visier_profile_management_python_sdk.pydantic.status import Status as StatusPydantic
from visier_profile_management_python_sdk.pydantic.local_tenant_profile_assignment_response_dto import LocalTenantProfileAssignmentResponseDTO as LocalTenantProfileAssignmentResponseDTOPydantic
from visier_profile_management_python_sdk.pydantic.local_tenant_profile_assignment_request_dto import LocalTenantProfileAssignmentRequestDTO as LocalTenantProfileAssignmentRequestDTOPydantic
from visier_profile_management_python_sdk.pydantic.local_tenant_profile_assignment_request_dto_target_user_ids import LocalTenantProfileAssignmentRequestDTOTargetUserIds as LocalTenantProfileAssignmentRequestDTOTargetUserIdsPydantic

from . import path

# Path params
ProfileIdSchema = schemas.StrSchema
RequestRequiredPathParams = typing_extensions.TypedDict(
    'RequestRequiredPathParams',
    {
        'profileId': typing.Union[ProfileIdSchema, str, ],
    }
)
RequestOptionalPathParams = typing_extensions.TypedDict(
    'RequestOptionalPathParams',
    {
    },
    total=False
)


class RequestPathParams(RequestRequiredPathParams, RequestOptionalPathParams):
    pass


request_path_profile_id = api_client.PathParameter(
    name="profileId",
    style=api_client.ParameterStyle.SIMPLE,
    schema=ProfileIdSchema,
    required=True,
)
# body param
SchemaForRequestBodyApplicationJson = LocalTenantProfileAssignmentRequestDTOSchema


request_body_local_tenant_profile_assignment_request_dto = api_client.RequestBody(
    content={
        'application/json': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJson),
    },
    required=True,
)
_auth = [
    'ApiKeyAuth',
    'BearerAuth',
    'CookieAuth',
    'OAuth2Auth',
    'OAuth2Auth',
]
SchemaFor200ResponseBodyApplicationJson = LocalTenantProfileAssignmentResponseDTOSchema


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    body: LocalTenantProfileAssignmentResponseDTO


@dataclass
class ApiResponseFor200Async(api_client.AsyncApiResponse):
    body: LocalTenantProfileAssignmentResponseDTO


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    response_cls_async=ApiResponseFor200Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJson),
    },
)
SchemaFor0ResponseBodyApplicationJson = StatusSchema


@dataclass
class ApiResponseForDefault(api_client.ApiResponse):
    body: Status


@dataclass
class ApiResponseForDefaultAsync(api_client.AsyncApiResponse):
    body: Status


_response_for_default = api_client.OpenApiResponse(
    response_cls=ApiResponseForDefault,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor0ResponseBodyApplicationJson),
    },
)
_status_code_to_response = {
    '200': _response_for_200,
    'default': _response_for_default,
}
_all_accept_content_types = (
    'application/json',
)


class BaseApi(api_client.Api):

    def _assign_profile_mapped_args(
        self,
        profile_id: str,
        target_user_ids: typing.Optional[LocalTenantProfileAssignmentRequestDTOTargetUserIds] = None,
        validity_start_time: typing.Optional[str] = None,
        validity_end_time: typing.Optional[str] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _path_params = {}
        _body = {}
        if target_user_ids is not None:
            _body["targetUserIds"] = target_user_ids
        if validity_start_time is not None:
            _body["validityStartTime"] = validity_start_time
        if validity_end_time is not None:
            _body["validityEndTime"] = validity_end_time
        args.body = _body
        if profile_id is not None:
            _path_params["profileId"] = profile_id
        args.path = _path_params
        return args

    async def _aassign_profile_oapg(
        self,
        body: typing.Any = None,
            path_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        ApiResponseForDefaultAsync,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        Assign a profile to a list of users
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestPathParams, path_params)
        used_path = path.value
    
        _path_params = {}
        for parameter in (
            request_path_profile_id,
        ):
            parameter_data = path_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _path_params.update(serialized_data)
    
        for k, v in _path_params.items():
            used_path = used_path.replace('{%s}' % k, v)
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'put'.upper()
        _headers.add('Content-Type', content_type)
    
        if body is schemas.unset:
            raise exceptions.ApiValueError(
                'The required body parameter has an invalid value of: unset. Set a valid value instead')
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/v1/admin/profiles/{profileId}/assign',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        serialized_data = request_body_local_tenant_profile_assignment_request_dto.serialize(body, content_type)
        if 'fields' in serialized_data:
            _fields = serialized_data['fields']
        elif 'body' in serialized_data:
            _body = serialized_data['body']
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            default_response = _status_code_to_response.get('default')
            if default_response:
                api_response = default_response.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
            else:
                api_response = api_client.ApiResponseWithoutDeserializationAsync(
                    response=response.http_response,
                    round_trip_time=response.round_trip_time,
                    status=response.http_response.status,
                    headers=response.http_response.headers,
                )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _assign_profile_oapg(
        self,
        body: typing.Any = None,
            path_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        ApiResponseForDefault,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        Assign a profile to a list of users
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestPathParams, path_params)
        used_path = path.value
    
        _path_params = {}
        for parameter in (
            request_path_profile_id,
        ):
            parameter_data = path_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _path_params.update(serialized_data)
    
        for k, v in _path_params.items():
            used_path = used_path.replace('{%s}' % k, v)
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'put'.upper()
        _headers.add('Content-Type', content_type)
    
        if body is schemas.unset:
            raise exceptions.ApiValueError(
                'The required body parameter has an invalid value of: unset. Set a valid value instead')
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/v1/admin/profiles/{profileId}/assign',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        serialized_data = request_body_local_tenant_profile_assignment_request_dto.serialize(body, content_type)
        if 'fields' in serialized_data:
            _fields = serialized_data['fields']
        elif 'body' in serialized_data:
            _body = serialized_data['body']
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            default_response = _status_code_to_response.get('default')
            if default_response:
                api_response = default_response.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
            else:
                api_response = api_client.ApiResponseWithoutDeserialization(
                    response=response.http_response,
                    round_trip_time=response.round_trip_time,
                    status=response.http_response.status,
                    headers=response.http_response.headers,
                )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class AssignProfileRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def aassign_profile(
        self,
        profile_id: str,
        target_user_ids: typing.Optional[LocalTenantProfileAssignmentRequestDTOTargetUserIds] = None,
        validity_start_time: typing.Optional[str] = None,
        validity_end_time: typing.Optional[str] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        ApiResponseForDefaultAsync,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._assign_profile_mapped_args(
            profile_id=profile_id,
            target_user_ids=target_user_ids,
            validity_start_time=validity_start_time,
            validity_end_time=validity_end_time,
        )
        return await self._aassign_profile_oapg(
            body=args.body,
            path_params=args.path,
            **kwargs,
        )
    
    def assign_profile(
        self,
        profile_id: str,
        target_user_ids: typing.Optional[LocalTenantProfileAssignmentRequestDTOTargetUserIds] = None,
        validity_start_time: typing.Optional[str] = None,
        validity_end_time: typing.Optional[str] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        ApiResponseForDefault,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._assign_profile_mapped_args(
            profile_id=profile_id,
            target_user_ids=target_user_ids,
            validity_start_time=validity_start_time,
            validity_end_time=validity_end_time,
        )
        return self._assign_profile_oapg(
            body=args.body,
            path_params=args.path,
        )

class AssignProfile(BaseApi):

    async def aassign_profile(
        self,
        profile_id: str,
        target_user_ids: typing.Optional[LocalTenantProfileAssignmentRequestDTOTargetUserIds] = None,
        validity_start_time: typing.Optional[str] = None,
        validity_end_time: typing.Optional[str] = None,
        validate: bool = False,
        **kwargs,
    ) -> LocalTenantProfileAssignmentResponseDTOPydantic:
        raw_response = await self.raw.aassign_profile(
            profile_id=profile_id,
            target_user_ids=target_user_ids,
            validity_start_time=validity_start_time,
            validity_end_time=validity_end_time,
            **kwargs,
        )
        if validate:
            return LocalTenantProfileAssignmentResponseDTOPydantic(**raw_response.body)
        return api_client.construct_model_instance(LocalTenantProfileAssignmentResponseDTOPydantic, raw_response.body)
    
    
    def assign_profile(
        self,
        profile_id: str,
        target_user_ids: typing.Optional[LocalTenantProfileAssignmentRequestDTOTargetUserIds] = None,
        validity_start_time: typing.Optional[str] = None,
        validity_end_time: typing.Optional[str] = None,
        validate: bool = False,
    ) -> LocalTenantProfileAssignmentResponseDTOPydantic:
        raw_response = self.raw.assign_profile(
            profile_id=profile_id,
            target_user_ids=target_user_ids,
            validity_start_time=validity_start_time,
            validity_end_time=validity_end_time,
        )
        if validate:
            return LocalTenantProfileAssignmentResponseDTOPydantic(**raw_response.body)
        return api_client.construct_model_instance(LocalTenantProfileAssignmentResponseDTOPydantic, raw_response.body)


class ApiForput(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def aput(
        self,
        profile_id: str,
        target_user_ids: typing.Optional[LocalTenantProfileAssignmentRequestDTOTargetUserIds] = None,
        validity_start_time: typing.Optional[str] = None,
        validity_end_time: typing.Optional[str] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        ApiResponseForDefaultAsync,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._assign_profile_mapped_args(
            profile_id=profile_id,
            target_user_ids=target_user_ids,
            validity_start_time=validity_start_time,
            validity_end_time=validity_end_time,
        )
        return await self._aassign_profile_oapg(
            body=args.body,
            path_params=args.path,
            **kwargs,
        )
    
    def put(
        self,
        profile_id: str,
        target_user_ids: typing.Optional[LocalTenantProfileAssignmentRequestDTOTargetUserIds] = None,
        validity_start_time: typing.Optional[str] = None,
        validity_end_time: typing.Optional[str] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        ApiResponseForDefault,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._assign_profile_mapped_args(
            profile_id=profile_id,
            target_user_ids=target_user_ids,
            validity_start_time=validity_start_time,
            validity_end_time=validity_end_time,
        )
        return self._assign_profile_oapg(
            body=args.body,
            path_params=args.path,
        )

