# coding: utf-8

"""
    Visier Profile Management APIs

    Visier APIs for managing the profiles assigned to users

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

import unittest

import visier_profile_management_python_sdk
from visier_profile_management_python_sdk.model.accessible_tenant_profile_assignment_response_dto import AccessibleTenantProfileAssignmentResponseDTO
from visier_profile_management_python_sdk import configuration


class TestAccessibleTenantProfileAssignmentResponseDTO(unittest.TestCase):
    """AccessibleTenantProfileAssignmentResponseDTO unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
