# coding: utf-8

# flake8: noqa

# import all models into this package
# if you have many models here with many references from one model to another this may
# raise a RecursionError
# to avoid this, import only the models that you directly need like:
# from from visier_profile_management_python_sdk.model.pet import Pet
# or import this package, but before doing it, use:
# import sys
# sys.setrecursionlimit(n)

from visier_profile_management_python_sdk.model.accessible_tenant_profile_assignment_request_dto import AccessibleTenantProfileAssignmentRequestDTO
from visier_profile_management_python_sdk.model.accessible_tenant_profile_assignment_request_dto_target_user_ids import AccessibleTenantProfileAssignmentRequestDTOTargetUserIds
from visier_profile_management_python_sdk.model.accessible_tenant_profile_assignment_response_dto import AccessibleTenantProfileAssignmentResponseDTO
from visier_profile_management_python_sdk.model.accessible_tenant_profile_revoke_request_dto import AccessibleTenantProfileRevokeRequestDTO
from visier_profile_management_python_sdk.model.accessible_tenant_profile_revoke_request_dto_target_user_ids import AccessibleTenantProfileRevokeRequestDTOTargetUserIds
from visier_profile_management_python_sdk.model.accessible_tenant_profile_revoke_response_dto import AccessibleTenantProfileRevokeResponseDTO
from visier_profile_management_python_sdk.model.additional_capabilities_dto import AdditionalCapabilitiesDTO
from visier_profile_management_python_sdk.model.additional_capabilities_dto_additional_capabilities import AdditionalCapabilitiesDTOAdditionalCapabilities
from visier_profile_management_python_sdk.model.all_profile_assigned_for_accessible_tenant_dto import AllProfileAssignedForAccessibleTenantDTO
from visier_profile_management_python_sdk.model.all_profile_assigned_for_local_tenant_dto import AllProfileAssignedForLocalTenantDTO
from visier_profile_management_python_sdk.model.capabilities_dto import CapabilitiesDTO
from visier_profile_management_python_sdk.model.error_dto import ErrorDTO
from visier_profile_management_python_sdk.model.failed_accessible_tenant_profile_assignment_dto import FailedAccessibleTenantProfileAssignmentDTO
from visier_profile_management_python_sdk.model.failed_local_tenant_profile_assignment_dto import FailedLocalTenantProfileAssignmentDTO
from visier_profile_management_python_sdk.model.failed_local_tenant_profile_revoke_dto import FailedLocalTenantProfileRevokeDTO
from visier_profile_management_python_sdk.model.google_protobuf_any import GoogleProtobufAny
from visier_profile_management_python_sdk.model.local_tenant_profile_assignment_request_dto import LocalTenantProfileAssignmentRequestDTO
from visier_profile_management_python_sdk.model.local_tenant_profile_assignment_request_dto_target_user_ids import LocalTenantProfileAssignmentRequestDTOTargetUserIds
from visier_profile_management_python_sdk.model.local_tenant_profile_assignment_response_dto import LocalTenantProfileAssignmentResponseDTO
from visier_profile_management_python_sdk.model.local_tenant_profile_revoke_request_dto import LocalTenantProfileRevokeRequestDTO
from visier_profile_management_python_sdk.model.local_tenant_profile_revoke_request_dto_target_user_ids import LocalTenantProfileRevokeRequestDTOTargetUserIds
from visier_profile_management_python_sdk.model.local_tenant_profile_revoke_response_dto import LocalTenantProfileRevokeResponseDTO
from visier_profile_management_python_sdk.model.profile_assigned_for_accessible_tenant_dto import ProfileAssignedForAccessibleTenantDTO
from visier_profile_management_python_sdk.model.profile_assigned_for_local_tenant_dto import ProfileAssignedForLocalTenantDTO
from visier_profile_management_python_sdk.model.profile_get_api_response_dto import ProfileGetAPIResponseDTO
from visier_profile_management_python_sdk.model.profile_get_api_response_dto_additional_capabilities import ProfileGetAPIResponseDTOAdditionalCapabilities
from visier_profile_management_python_sdk.model.profiles_get_api_response_dto import ProfilesGetAPIResponseDTO
from visier_profile_management_python_sdk.model.reduced_error_dto import ReducedErrorDTO
from visier_profile_management_python_sdk.model.reduced_tenant_code_error_dto import ReducedTenantCodeErrorDTO
from visier_profile_management_python_sdk.model.reduced_user_id_error_dto import ReducedUserIdErrorDTO
from visier_profile_management_python_sdk.model.status import Status
from visier_profile_management_python_sdk.model.successful_accessible_tenant_profile_assignment_dto import SuccessfulAccessibleTenantProfileAssignmentDTO
from visier_profile_management_python_sdk.model.successful_local_tenant_profile_assignment_dto import SuccessfulLocalTenantProfileAssignmentDTO
from visier_profile_management_python_sdk.model.target_tenant_code_dto import TargetTenantCodeDTO
from visier_profile_management_python_sdk.model.tenant_code_error_dto import TenantCodeErrorDTO
from visier_profile_management_python_sdk.model.user_id_error_dto import UserIdErrorDTO
