# coding: utf-8

"""
    Visier Profile Management APIs

    Visier APIs for managing the profiles assigned to users

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from visier_profile_management_python_sdk.pydantic.accessible_tenant_profile_assignment_request_dto_target_user_ids import AccessibleTenantProfileAssignmentRequestDTOTargetUserIds
from visier_profile_management_python_sdk.pydantic.target_tenant_code_dto import TargetTenantCodeDTO

class AccessibleTenantProfileAssignmentRequestDTO(BaseModel):
    target_user_ids: typing.Optional[AccessibleTenantProfileAssignmentRequestDTOTargetUserIds] = Field(None, alias='targetUserIds')

    # A list of objects representing the  analytic tenants for profiles assigned to the users.
    target_tenant_codes: typing.Optional[typing.List[TargetTenantCodeDTO]] = Field(None, alias='targetTenantCodes')

    # An inclusive date-time when this profile is active.
    validity_start_time: typing.Optional[str] = Field(None, alias='validityStartTime')

    # An exclusive date-time when this profile is no longer active.
    validity_end_time: typing.Optional[str] = Field(None, alias='validityEndTime')
    class Config:
        arbitrary_types_allowed = True
