# coding: utf-8

"""
    Visier Profile Management APIs

    Visier APIs for managing the profiles assigned to users

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from visier_profile_management_python_sdk.pydantic.failed_accessible_tenant_profile_assignment_dto import FailedAccessibleTenantProfileAssignmentDTO
from visier_profile_management_python_sdk.pydantic.successful_accessible_tenant_profile_assignment_dto import SuccessfulAccessibleTenantProfileAssignmentDTO
from visier_profile_management_python_sdk.pydantic.tenant_code_error_dto import TenantCodeErrorDTO
from visier_profile_management_python_sdk.pydantic.user_id_error_dto import UserIdErrorDTO

class AccessibleTenantProfileAssignmentResponseDTO(BaseModel):
    # If true, an error is generated by the request.
    errors: typing.Optional[bool] = Field(None, alias='errors')

    # A list of objects representing any tenants that returned errors.
    bad_tenant_codes: typing.Optional[typing.List[TenantCodeErrorDTO]] = Field(None, alias='badTenantCodes')

    # A list of objects representing the user IDs that may not be valid.
    bad_user_ids: typing.Optional[typing.List[UserIdErrorDTO]] = Field(None, alias='badUserIds')

    # A list of objects representing any errors during the assignment operation.
    failed_assignments: typing.Optional[typing.List[FailedAccessibleTenantProfileAssignmentDTO]] = Field(None, alias='failedAssignments')

    # A list of user IDs that were successfully assigned the profiles.
    successful_assignments: typing.Optional[typing.List[SuccessfulAccessibleTenantProfileAssignmentDTO]] = Field(None, alias='successfulAssignments')
    class Config:
        arbitrary_types_allowed = True
