# coding: utf-8

"""
    Visier Profile Management APIs

    Visier APIs for managing the profiles assigned to users

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from visier_profile_management_python_sdk.pydantic.reduced_tenant_code_error_dto import ReducedTenantCodeErrorDTO
from visier_profile_management_python_sdk.pydantic.reduced_user_id_error_dto import ReducedUserIdErrorDTO
from visier_profile_management_python_sdk.pydantic.successful_local_tenant_profile_assignment_dto import SuccessfulLocalTenantProfileAssignmentDTO

class AccessibleTenantProfileRevokeResponseDTO(BaseModel):
    # A list of objects representing any tenants that returned errors.
    bad_tenant_codes: typing.Optional[typing.List[ReducedTenantCodeErrorDTO]] = Field(None, alias='badTenantCodes')

    # A list of objects representing the user IDs that may not be valid.
    bad_user_ids: typing.Optional[typing.List[ReducedUserIdErrorDTO]] = Field(None, alias='badUserIds')

    # A list of objects representing the valid user IDs that were not affected.
    unaffected_users: typing.Optional[typing.List[SuccessfulLocalTenantProfileAssignmentDTO]] = Field(None, alias='unaffectedUsers')

    # A list of objects representing the valid user IDs that succeeded.
    succeeded: typing.Optional[typing.List[SuccessfulLocalTenantProfileAssignmentDTO]] = Field(None, alias='succeeded')
    class Config:
        arbitrary_types_allowed = True
