# coding: utf-8

"""
    Visier Profile Management APIs

    Visier APIs for managing the profiles assigned to users

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from visier_profile_management_python_sdk.pydantic.profile_assigned_for_accessible_tenant_dto import ProfileAssignedForAccessibleTenantDTO

class AllProfileAssignedForAccessibleTenantDTO(BaseModel):
    # A list of objects representing the user profiles assigned to the user and their validity range.
    assigned_profiles_for_accessible_tenant: typing.Optional[typing.List[ProfileAssignedForAccessibleTenantDTO]] = Field(None, alias='assignedProfilesForAccessibleTenant')
    class Config:
        arbitrary_types_allowed = True
