# coding: utf-8

"""
    Visier Profile Management APIs

    Visier APIs for managing the profiles assigned to users

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from visier_profile_management_python_sdk.pydantic.error_dto import ErrorDTO

class FailedLocalTenantProfileAssignmentDTO(BaseModel):
    # The impacted user ID.
    user_id: typing.Optional[str] = Field(None, alias='userId')

    # The details about the error.
    error: typing.Optional[ErrorDTO] = Field(None, alias='error')
    class Config:
        arbitrary_types_allowed = True
