# coding: utf-8

"""
    Visier Profile Management APIs

    Visier APIs for managing the profiles assigned to users

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from visier_profile_management_python_sdk.pydantic.failed_local_tenant_profile_revoke_dto import FailedLocalTenantProfileRevokeDTO
from visier_profile_management_python_sdk.pydantic.successful_local_tenant_profile_assignment_dto import SuccessfulLocalTenantProfileAssignmentDTO

class LocalTenantProfileRevokeResponseDTO(BaseModel):
    # A list of objects representing any errors that occurred during the assignment operation.
    failed: typing.Optional[typing.List[FailedLocalTenantProfileRevokeDTO]] = Field(None, alias='failed')

    # A list of the user IDs that successfully had a profile removed.
    succeeded: typing.Optional[typing.List[SuccessfulLocalTenantProfileAssignmentDTO]] = Field(None, alias='succeeded')
    class Config:
        arbitrary_types_allowed = True
