# coding: utf-8

"""
    Visier Profile Management APIs

    Visier APIs for managing the profiles assigned to users

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from visier_profile_management_python_sdk.pydantic.failed_local_tenant_profile_assignment_dto import FailedLocalTenantProfileAssignmentDTO
from visier_profile_management_python_sdk.pydantic.successful_local_tenant_profile_assignment_dto import SuccessfulLocalTenantProfileAssignmentDTO
from visier_profile_management_python_sdk.pydantic.user_id_error_dto import UserIdErrorDTO

class LocalTenantProfileAssignmentResponseDTO(BaseModel):
    # If true, an error was generated by the request.
    errors: typing.Optional[bool] = Field(None, alias='errors')

    # A list of objects representing the user IDs that may not be valid.
    bad_user_ids: typing.Optional[typing.List[UserIdErrorDTO]] = Field(None, alias='badUserIds')

    # A list of objects representing any errors that occurred during the assignment operation.
    failed_assignments: typing.Optional[typing.List[FailedLocalTenantProfileAssignmentDTO]] = Field(None, alias='failedAssignments')

    # A list of the user IDs that were successfully assigned the profile.
    successful_assignments: typing.Optional[typing.List[SuccessfulLocalTenantProfileAssignmentDTO]] = Field(None, alias='successfulAssignments')
    class Config:
        arbitrary_types_allowed = True
