# coding: utf-8

"""
    Visier Profile Management APIs

    Visier APIs for managing the profiles assigned to users

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from visier_profile_management_python_sdk.pydantic.capabilities_dto import CapabilitiesDTO
from visier_profile_management_python_sdk.pydantic.profile_get_api_response_dto_additional_capabilities import ProfileGetAPIResponseDTOAdditionalCapabilities

class ProfileGetAPIResponseDTO(BaseModel):
    # The unique identifier associated with the profile.
    profile_id: typing.Optional[str] = Field(None, alias='profileId')

    # An identifiable profile name to display in Visier. For example, \"Partner Service Manager\".
    display_name: typing.Optional[str] = Field(None, alias='displayName')

    # A list of objects representing the access that this profile has for the capabilities of this profile.
    capabilities: typing.Optional[typing.List[CapabilitiesDTO]] = Field(None, alias='capabilities')

    additional_capabilities: typing.Optional[ProfileGetAPIResponseDTOAdditionalCapabilities] = Field(None, alias='additionalCapabilities')
    class Config:
        arbitrary_types_allowed = True
