# coding: utf-8

"""
    Visier Profile Management APIs

    Visier APIs for managing the profiles assigned to users

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class SuccessfulAccessibleTenantProfileAssignmentDTO(BaseModel):
    # The user ID.
    user_id: typing.Optional[str] = Field(None, alias='userId')

    # The tenant code.
    tenant_code: typing.Optional[str] = Field(None, alias='tenantCode')

    # If true, the target assignment is for all analytic tenants.
    for_all_children: typing.Optional[bool] = Field(None, alias='forAllChildren')
    class Config:
        arbitrary_types_allowed = True
