# coding: utf-8

"""
    Visier Profile Management APIs

    Visier APIs for managing the profiles assigned to users

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class TargetTenantCodeDTO(BaseModel):
    # The tenant code.
    tenant_code: typing.Optional[str] = Field(None, alias='tenantCode')

    # If true, the assignment is for all the analytic tenants of the specified tenant.
    for_all_children: typing.Optional[bool] = Field(None, alias='forAllChildren')
    class Config:
        arbitrary_types_allowed = True
