# coding: utf-8

# flake8: noqa

"""
    Visier Profile Management APIs

    Visier APIs for managing the profiles assigned to users

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

__version__ = "22222222.99201.1200"

# import ApiClient
from visier_profile_management_python_sdk.api_client import ApiClient

# import Configuration
from visier_profile_management_python_sdk.configuration import Configuration

# import exceptions
from visier_profile_management_python_sdk.exceptions import OpenApiException
from visier_profile_management_python_sdk.exceptions import ApiAttributeError
from visier_profile_management_python_sdk.exceptions import ApiTypeError
from visier_profile_management_python_sdk.exceptions import ApiValueError
from visier_profile_management_python_sdk.exceptions import ApiKeyError
from visier_profile_management_python_sdk.exceptions import ApiException

from visier_profile_management_python_sdk.client import VisierProfileManagement
