# coding: utf-8
"""
    Visier Profile Management APIs

    Visier APIs for managing the profiles assigned to users

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

import typing
import inspect
from datetime import date, datetime
from visier_profile_management_python_sdk.client_custom import ClientCustom
from visier_profile_management_python_sdk.configuration import Configuration
from visier_profile_management_python_sdk.api_client import ApiClient
from visier_profile_management_python_sdk.type_util import copy_signature
from visier_profile_management_python_sdk.apis.tags.profile_management_api import ProfileManagementApi



class VisierProfileManagement(ClientCustom):

    def __init__(self, configuration: typing.Union[Configuration, None] = None, **kwargs):
        super().__init__(configuration, **kwargs)
        if (len(kwargs) > 0):
            configuration = Configuration(**kwargs)
        if (configuration is None):
            raise Exception("configuration is required")
        api_client = ApiClient(configuration)
        self.profile_management: ProfileManagementApi = ProfileManagementApi(api_client)
