# coding: utf-8

"""
    Visier Profile Management APIs

    Visier APIs for managing the profiles assigned to users

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from visier_profile_management_python_sdk.paths.v1_admin_profiles_accessible_tenants_profile_id_assign.put import AssignAnalyticProfileRaw
from visier_profile_management_python_sdk.paths.v1_admin_profiles_profile_id_assign.put import AssignProfileRaw
from visier_profile_management_python_sdk.paths.v1_admin_profiles.get import GetAllProfilesRaw
from visier_profile_management_python_sdk.paths.v1_admin_profiles_accessible_tenants_profile_id.get import GetAnalyticProfileDetailRaw
from visier_profile_management_python_sdk.paths.v1_admin_profiles_accessible_tenants.get import GetAnalyticProfilesRaw
from visier_profile_management_python_sdk.paths.v1_admin_users_user_id_accessible_tenant_profiles.get import GetAnalyticUserProfileRaw
from visier_profile_management_python_sdk.paths.v1_admin_profiles_profile_id.get import GetProfileDetailRaw
from visier_profile_management_python_sdk.paths.v1_admin_users_user_id_profiles.get import GetUserProfileRaw
from visier_profile_management_python_sdk.paths.v1_admin_profiles_accessible_tenants_profile_id_remove.delete import RemoveAnalyticProfileRaw
from visier_profile_management_python_sdk.paths.v1_admin_profiles_profile_id_remove.delete import RemoveProfileRaw


class ProfileManagementApiRaw(
    AssignAnalyticProfileRaw,
    AssignProfileRaw,
    GetAllProfilesRaw,
    GetAnalyticProfileDetailRaw,
    GetAnalyticProfilesRaw,
    GetAnalyticUserProfileRaw,
    GetProfileDetailRaw,
    GetUserProfileRaw,
    RemoveAnalyticProfileRaw,
    RemoveProfileRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
