# coding: utf-8

"""
    Visier Profile Management APIs

    Visier APIs for managing the profiles assigned to users

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from visier_profile_management_python_sdk.paths.v1_admin_profiles_accessible_tenants_profile_id_assign.put import AssignAnalyticProfile
from visier_profile_management_python_sdk.paths.v1_admin_profiles_profile_id_assign.put import AssignProfile
from visier_profile_management_python_sdk.paths.v1_admin_profiles.get import GetAllProfiles
from visier_profile_management_python_sdk.paths.v1_admin_profiles_accessible_tenants_profile_id.get import GetAnalyticProfileDetail
from visier_profile_management_python_sdk.paths.v1_admin_profiles_accessible_tenants.get import GetAnalyticProfiles
from visier_profile_management_python_sdk.paths.v1_admin_users_user_id_accessible_tenant_profiles.get import GetAnalyticUserProfile
from visier_profile_management_python_sdk.paths.v1_admin_profiles_profile_id.get import GetProfileDetail
from visier_profile_management_python_sdk.paths.v1_admin_users_user_id_profiles.get import GetUserProfile
from visier_profile_management_python_sdk.paths.v1_admin_profiles_accessible_tenants_profile_id_remove.delete import RemoveAnalyticProfile
from visier_profile_management_python_sdk.paths.v1_admin_profiles_profile_id_remove.delete import RemoveProfile
from visier_profile_management_python_sdk.apis.tags.profile_management_api_raw import ProfileManagementApiRaw


class ProfileManagementApi(
    AssignAnalyticProfile,
    AssignProfile,
    GetAllProfiles,
    GetAnalyticProfileDetail,
    GetAnalyticProfiles,
    GetAnalyticUserProfile,
    GetProfileDetail,
    GetUserProfile,
    RemoveAnalyticProfile,
    RemoveProfile,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ProfileManagementApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ProfileManagementApiRaw(api_client)
