# coding: utf-8

"""
    Visier Profile Management APIs

    Visier APIs for managing the profiles assigned to users

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_profile_management_python_sdk.type.accessible_tenant_profile_assignment_request_dto_target_user_ids import AccessibleTenantProfileAssignmentRequestDTOTargetUserIds
from visier_profile_management_python_sdk.type.target_tenant_code_dto import TargetTenantCodeDTO

class RequiredAccessibleTenantProfileAssignmentRequestDTO(TypedDict):
    pass

class OptionalAccessibleTenantProfileAssignmentRequestDTO(TypedDict, total=False):
    targetUserIds: AccessibleTenantProfileAssignmentRequestDTOTargetUserIds

    # A list of objects representing the  analytic tenants for profiles assigned to the users.
    targetTenantCodes: typing.List[TargetTenantCodeDTO]

    # An inclusive date-time when this profile is active.
    validityStartTime: str

    # An exclusive date-time when this profile is no longer active.
    validityEndTime: str

class AccessibleTenantProfileAssignmentRequestDTO(RequiredAccessibleTenantProfileAssignmentRequestDTO, OptionalAccessibleTenantProfileAssignmentRequestDTO):
    pass
