# coding: utf-8

"""
    Visier Profile Management APIs

    Visier APIs for managing the profiles assigned to users

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_profile_management_python_sdk.type.reduced_tenant_code_error_dto import ReducedTenantCodeErrorDTO
from visier_profile_management_python_sdk.type.reduced_user_id_error_dto import ReducedUserIdErrorDTO
from visier_profile_management_python_sdk.type.successful_local_tenant_profile_assignment_dto import SuccessfulLocalTenantProfileAssignmentDTO

class RequiredAccessibleTenantProfileRevokeResponseDTO(TypedDict):
    pass

class OptionalAccessibleTenantProfileRevokeResponseDTO(TypedDict, total=False):
    # A list of objects representing any tenants that returned errors.
    badTenantCodes: typing.List[ReducedTenantCodeErrorDTO]

    # A list of objects representing the user IDs that may not be valid.
    badUserIds: typing.List[ReducedUserIdErrorDTO]

    # A list of objects representing the valid user IDs that were not affected.
    unaffectedUsers: typing.List[SuccessfulLocalTenantProfileAssignmentDTO]

    # A list of objects representing the valid user IDs that succeeded.
    succeeded: typing.List[SuccessfulLocalTenantProfileAssignmentDTO]

class AccessibleTenantProfileRevokeResponseDTO(RequiredAccessibleTenantProfileRevokeResponseDTO, OptionalAccessibleTenantProfileRevokeResponseDTO):
    pass
