# coding: utf-8

"""
    Visier Profile Management APIs

    Visier APIs for managing the profiles assigned to users

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_profile_management_python_sdk.type.failed_accessible_tenant_profile_assignment_dto import FailedAccessibleTenantProfileAssignmentDTO
from visier_profile_management_python_sdk.type.successful_accessible_tenant_profile_assignment_dto import SuccessfulAccessibleTenantProfileAssignmentDTO
from visier_profile_management_python_sdk.type.tenant_code_error_dto import TenantCodeErrorDTO
from visier_profile_management_python_sdk.type.user_id_error_dto import UserIdErrorDTO

class RequiredAccessibleTenantProfileAssignmentResponseDTO(TypedDict):
    pass

class OptionalAccessibleTenantProfileAssignmentResponseDTO(TypedDict, total=False):
    # If true, an error is generated by the request.
    errors: bool

    # A list of objects representing any tenants that returned errors.
    badTenantCodes: typing.List[TenantCodeErrorDTO]

    # A list of objects representing the user IDs that may not be valid.
    badUserIds: typing.List[UserIdErrorDTO]

    # A list of objects representing any errors during the assignment operation.
    failedAssignments: typing.List[FailedAccessibleTenantProfileAssignmentDTO]

    # A list of user IDs that were successfully assigned the profiles.
    successfulAssignments: typing.List[SuccessfulAccessibleTenantProfileAssignmentDTO]

class AccessibleTenantProfileAssignmentResponseDTO(RequiredAccessibleTenantProfileAssignmentResponseDTO, OptionalAccessibleTenantProfileAssignmentResponseDTO):
    pass
