# coding: utf-8

"""
    Visier Profile Management APIs

    Visier APIs for managing the profiles assigned to users

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_profile_management_python_sdk.type.profile_assigned_for_accessible_tenant_dto import ProfileAssignedForAccessibleTenantDTO

class RequiredAllProfileAssignedForAccessibleTenantDTO(TypedDict):
    pass

class OptionalAllProfileAssignedForAccessibleTenantDTO(TypedDict, total=False):
    # A list of objects representing the user profiles assigned to the user and their validity range.
    assignedProfilesForAccessibleTenant: typing.List[ProfileAssignedForAccessibleTenantDTO]

class AllProfileAssignedForAccessibleTenantDTO(RequiredAllProfileAssignedForAccessibleTenantDTO, OptionalAllProfileAssignedForAccessibleTenantDTO):
    pass
