# coding: utf-8

"""
    Visier Profile Management APIs

    Visier APIs for managing the profiles assigned to users

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredErrorDTO(TypedDict):
    pass

class OptionalErrorDTO(TypedDict, total=False):
    # The root cause identifier that allows Visier to determine the source of the problem.
    rootCauseId: str

    # A brief identifier of the type of error.
    errorCode: str

    # A description of the error that occurred.
    errorMessage: str

class ErrorDTO(RequiredErrorDTO, OptionalErrorDTO):
    pass
