# coding: utf-8

"""
    Visier Profile Management APIs

    Visier APIs for managing the profiles assigned to users

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_profile_management_python_sdk.type.error_dto import ErrorDTO

class RequiredFailedLocalTenantProfileAssignmentDTO(TypedDict):
    pass

class OptionalFailedLocalTenantProfileAssignmentDTO(TypedDict, total=False):
    # The impacted user ID.
    userId: str

    # The details about the error.
    error: ErrorDTO

class FailedLocalTenantProfileAssignmentDTO(RequiredFailedLocalTenantProfileAssignmentDTO, OptionalFailedLocalTenantProfileAssignmentDTO):
    pass
