# coding: utf-8

"""
    Visier Profile Management APIs

    Visier APIs for managing the profiles assigned to users

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_profile_management_python_sdk.type.error_dto import ErrorDTO

class RequiredFailedAccessibleTenantProfileAssignmentDTO(TypedDict):
    pass

class OptionalFailedAccessibleTenantProfileAssignmentDTO(TypedDict, total=False):
    # The impacted user ID.
    userId: str

    # The tenant code.
    tenantCode: str

    # If true, the target assignment is for all analytic tenants.
    forAllChildren: bool

    # The details about the error.
    error: ErrorDTO

class FailedAccessibleTenantProfileAssignmentDTO(RequiredFailedAccessibleTenantProfileAssignmentDTO, OptionalFailedAccessibleTenantProfileAssignmentDTO):
    pass
