# coding: utf-8

"""
    Visier Profile Management APIs

    Visier APIs for managing the profiles assigned to users

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_profile_management_python_sdk.type.failed_local_tenant_profile_assignment_dto import FailedLocalTenantProfileAssignmentDTO
from visier_profile_management_python_sdk.type.successful_local_tenant_profile_assignment_dto import SuccessfulLocalTenantProfileAssignmentDTO
from visier_profile_management_python_sdk.type.user_id_error_dto import UserIdErrorDTO

class RequiredLocalTenantProfileAssignmentResponseDTO(TypedDict):
    pass

class OptionalLocalTenantProfileAssignmentResponseDTO(TypedDict, total=False):
    # If true, an error was generated by the request.
    errors: bool

    # A list of objects representing the user IDs that may not be valid.
    badUserIds: typing.List[UserIdErrorDTO]

    # A list of objects representing any errors that occurred during the assignment operation.
    failedAssignments: typing.List[FailedLocalTenantProfileAssignmentDTO]

    # A list of the user IDs that were successfully assigned the profile.
    successfulAssignments: typing.List[SuccessfulLocalTenantProfileAssignmentDTO]

class LocalTenantProfileAssignmentResponseDTO(RequiredLocalTenantProfileAssignmentResponseDTO, OptionalLocalTenantProfileAssignmentResponseDTO):
    pass
