# coding: utf-8

"""
    Visier Profile Management APIs

    Visier APIs for managing the profiles assigned to users

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_profile_management_python_sdk.type.local_tenant_profile_revoke_request_dto_target_user_ids import LocalTenantProfileRevokeRequestDTOTargetUserIds

class RequiredLocalTenantProfileRevokeRequestDTO(TypedDict):
    pass

class OptionalLocalTenantProfileRevokeRequestDTO(TypedDict, total=False):
    targetUserIds: LocalTenantProfileRevokeRequestDTOTargetUserIds

class LocalTenantProfileRevokeRequestDTO(RequiredLocalTenantProfileRevokeRequestDTO, OptionalLocalTenantProfileRevokeRequestDTO):
    pass
