# coding: utf-8

"""
    Visier Profile Management APIs

    Visier APIs for managing the profiles assigned to users

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_profile_management_python_sdk.type.local_tenant_profile_assignment_request_dto_target_user_ids import LocalTenantProfileAssignmentRequestDTOTargetUserIds

class RequiredLocalTenantProfileAssignmentRequestDTO(TypedDict):
    pass

class OptionalLocalTenantProfileAssignmentRequestDTO(TypedDict, total=False):
    targetUserIds: LocalTenantProfileAssignmentRequestDTOTargetUserIds

    # An inclusive date-time when this profile is active.
    validityStartTime: str

    # An exclusive date-time when this profile is no longer active.
    validityEndTime: str

class LocalTenantProfileAssignmentRequestDTO(RequiredLocalTenantProfileAssignmentRequestDTO, OptionalLocalTenantProfileAssignmentRequestDTO):
    pass
