# coding: utf-8

"""
    Visier Profile Management APIs

    Visier APIs for managing the profiles assigned to users

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_profile_management_python_sdk.type.profile_get_api_response_dto import ProfileGetAPIResponseDTO

class RequiredProfilesGetAPIResponseDTO(TypedDict):
    pass

class OptionalProfilesGetAPIResponseDTO(TypedDict, total=False):
    # A list of objects representing the available profiles.
    profiles: typing.List[ProfileGetAPIResponseDTO]

class ProfilesGetAPIResponseDTO(RequiredProfilesGetAPIResponseDTO, OptionalProfilesGetAPIResponseDTO):
    pass
