# coding: utf-8

"""
    Visier Profile Management APIs

    Visier APIs for managing the profiles assigned to users

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_profile_management_python_sdk.type.capabilities_dto import CapabilitiesDTO
from visier_profile_management_python_sdk.type.profile_get_api_response_dto_additional_capabilities import ProfileGetAPIResponseDTOAdditionalCapabilities

class RequiredProfileGetAPIResponseDTO(TypedDict):
    pass

class OptionalProfileGetAPIResponseDTO(TypedDict, total=False):
    # The unique identifier associated with the profile.
    profileId: str

    # An identifiable profile name to display in Visier. For example, \"Partner Service Manager\".
    displayName: str

    # A list of objects representing the access that this profile has for the capabilities of this profile.
    capabilities: typing.List[CapabilitiesDTO]

    additionalCapabilities: ProfileGetAPIResponseDTOAdditionalCapabilities

class ProfileGetAPIResponseDTO(RequiredProfileGetAPIResponseDTO, OptionalProfileGetAPIResponseDTO):
    pass
