# coding: utf-8

"""
    Visier Profile Management APIs

    Visier APIs for managing the profiles assigned to users

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredProfileAssignedForAccessibleTenantDTO(TypedDict):
    pass

class OptionalProfileAssignedForAccessibleTenantDTO(TypedDict, total=False):
    # The unique identifier associated with the profile.
    profileId: str

    # An identifiable profile name to display in Visier such as \"Partner Service Manager\".
    displayName: str

    # The tenant code of the analytic tenant on which this profile is assigned.
    tenantCode: str

    # If true, the profile is assigned for all the analytic tenants of the administrating tenant.
    forAllChildren: bool

    # An inclusive date-time when this profile is active.   Note: Long.Min_Value means that startTime is undefined.
    validityStartTime: str

    # An exclusive date-time when this profile is no longer active.   Note: Long.Max_Value means that endTime is undefined and is equivalent to permanent access.
    validityEndTime: str

class ProfileAssignedForAccessibleTenantDTO(RequiredProfileAssignedForAccessibleTenantDTO, OptionalProfileAssignedForAccessibleTenantDTO):
    pass
