# coding: utf-8

"""
    Visier Profile Management APIs

    Visier APIs for managing the profiles assigned to users

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_profile_management_python_sdk.type.reduced_error_dto import ReducedErrorDTO

class RequiredReducedTenantCodeErrorDTO(TypedDict):
    pass

class OptionalReducedTenantCodeErrorDTO(TypedDict, total=False):
    # The bad tenant code.
    tenantCode: str

    # If true, the assignment is for all the analytic tenants of the specified tenant.
    forAllChildren: bool

    # The details about the error.
    error: ReducedErrorDTO

class ReducedTenantCodeErrorDTO(RequiredReducedTenantCodeErrorDTO, OptionalReducedTenantCodeErrorDTO):
    pass
