# coding: utf-8

"""
    Visier Profile Management APIs

    Visier APIs for managing the profiles assigned to users

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_profile_management_python_sdk.type.reduced_error_dto import ReducedErrorDTO

class RequiredReducedUserIdErrorDTO(TypedDict):
    pass

class OptionalReducedUserIdErrorDTO(TypedDict, total=False):
    # The bad user ID.
    userId: str

    # The details about the error.
    error: ReducedErrorDTO

class ReducedUserIdErrorDTO(RequiredReducedUserIdErrorDTO, OptionalReducedUserIdErrorDTO):
    pass
